name: Update README Daily

on:
  schedule:
    # Esecuzione ogni giorno alle 11:00 UTC, che corrisponde a 12:00 ora italiana (considerando l'ora legale)
    - cron: '0 11 * * *'

permissions:
  contents: write  # Concede permessi di scrittura sui contenuti del repository

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Usa il token con permessi di scrittura
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install PyGithub

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          python scripts/update_readme.py

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --cached --exit-code; then
            echo "No changes to commit."
          else
            git commit -m "Update README with latest repository statuses"
            git push origin HEAD:${{ github.ref }}
          fi
